---
- name: Create MySQL Docker container for WordPress
  community.docker.docker_container:
    name: mysql_container
    image: mysql:5.7
    state: started
    restart_policy: always
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_db_name }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
    ports:
      - "3306:3306"
  tags: install
