prometheus_image: "prom/prometheus:latest"
prometheus_container_name: "prometheus"
prometheus_port: "9090"               # Порт за Prometheus вътре в контейнера
prometheus_host_port: "9090"           # Порт на хоста, на който ще бъде достъпен Prometheus
prometheus_config_file: "/etc/prometheus/prometheus.yml"  # Път до конфигурационния файл в контейнера
