---
- name: Deploy Nginx as reverse proxy
  community.docker.docker_container:
    name: nginx_proxy
    image: nginx:latest
    state: started
    restart_policy: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  tags: proxy
